version: '3.7'
services:
  flab-db:
    image: library/mysql:8.0
    container_name: flab-db
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: flab
      MYSQL_ROOT_PASSWORD: flab
      MYSQL_USER: user-management
      MYSQL_PASSWORD: 1q2w3e4r@@
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    platform: linux/x86_64